services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: qwerty
      ME_CONFIG_MONGODB_SERVER: mongodb
  docker-testapp:
    build: .
    image: pardeepksharma/express-testapp
    ports:
      - 5051:5050
    depends_on:
      - mongodb
